apiVersion: v1
kind: Secret
metadata:
  name: bmh-2
type: Opaque
stringData:
  username: jsj
  password: ckddmlrhks401!

---

apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bmh-1
spec:
  online: true
  bootMACAddress: a4:bf:01:71:45:f9
  # This particular hardware does not support UEFI so we use legacy
  bootMode: legacy
  bmc:
    address: ipmi://192.168.40.8
    credentialsName: bmh-2
    disableCertificateVerification: true
