apiVersion: v1
kind: Secret
metadata:
  name: bmh-1
type: Opaque
stringData:
  username: root
  password: ckddmlrhks401!

---

apiVersion: metal3.io/v1alpha1
kind: BareMetalHost
metadata:
  name: bmh-1
spec:
  online: true
  bootMACAddress: a4:bf:01:74:55:e6
  # This particular hardware does not support UEFI so we use legacy
  bootMode: legacy
  bmc:
    address: ipmi://192.168.40.58
    credentialsName: bmh-1
    disableCertificateVerification: true
