apiVersion: cluster.x-k8s.io/v1beta1
kind: Cluster
metadata:
  name: workload1
  namespace: default
spec:
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.10.0/24
    serviceDomain: cluster.local
    services:
      cidrBlocks:
      - 10.96.0.0/12
  controlPlaneRef:
    apiVersion: controlplane.cluster.x-k8s.io/v1beta1
    kind: KubeadmControlPlane
    name: workload1
    namespace: default
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
    kind: Metal3Cluster
    name: workload1
    namespace: default
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3Cluster
metadata:
  name: workload1
  namespace: default
spec:
  controlPlaneEndpoint:
    host: 192.168.40.137
    port: 6443
  noCloudProvider: true
---
apiVersion: controlplane.cluster.x-k8s.io/v1beta1
kind: KubeadmControlPlane
metadata:
  name: workload1
  namespace: default
spec:
  kubeadmConfigSpec:
    initConfiguration:
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: metal3.io/uuid={{ ds.meta_data.uuid }}
        name: '{{ ds.meta_data.name }}'
    joinConfiguration:
      controlPlane: {}
      nodeRegistration:
        kubeletExtraArgs:
          node-labels: metal3.io/uuid={{ ds.meta_data.uuid }}
        name: '{{ ds.meta_data.name }}'
    users:
    - name: user
      sshAuthorizedKeys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFAVpbLhDAyF18/LDnRM1t5ZfMuFYgQlEBccATym2VH5
        root@compute-07
      sudo: ALL=(ALL) NOPASSWD:ALL
      groups: sudo
    preKubeadmCommands:
    - sudo su -
    - resolvectl dns eno1 8.8.8.8 1.1.1.1
    - cp /etc/netplan/50-cloud-init.yaml /etc/netplan/50-cloud-init.yaml.bak
    - |
      cat <<EOF | sudo tee /etc/netplan/50-cloud-init.yaml > /dev/null
      network:
          ethernets:
              eno1:
                  dhcp4: true
                  dhcp6: true
              eno2:
                  addresses:
                  - 192.168.40.137/24
                  nameservers:
                      addresses:
                      - 8.8.8.8
                      search: []
                  routes:
                  -   to: default
                      via: 192.168.40.1
          version: 2
      EOF
    - sudo netplan apply
  machineTemplate:
    infrastructureRef:
      apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
      kind: Metal3MachineTemplate
      name: workload1-controlplane
      namespace: default
    nodeDrainTimeout: 0s
  replicas: 1
  rolloutStrategy:
    rollingUpdate:
      maxSurge: 1
    type: RollingUpdate
  version: v1.29.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: workload1-controlplane
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      dataTemplate:
        name: workload1-controlplane-template
      image:
        checksum: d92df03e7820c553ddcee2680d5d4798b4e7957fd0375b5d1d24b8241532082b
        checksumType: sha256
        format: qcow2
        url: http://192.168.40.241/UBUNTU_22.04_NODE_IMAGE_K8S_v1.29.0.qcow2
---
apiVersion: cluster.x-k8s.io/v1beta1
kind: MachineDeployment
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: workload1
    nodepool: nodepool-0
  name: workload1
  namespace: default
spec:
  clusterName: workload1
  replicas: 0
  selector:
    matchLabels:
      cluster.x-k8s.io/cluster-name: workload1
      nodepool: nodepool-0
  template:
    metadata:
      labels:
        cluster.x-k8s.io/cluster-name: workload1
        nodepool: nodepool-0
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfigTemplate
          name: workload1-workers
      clusterName: workload1
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: Metal3MachineTemplate
        name: workload1-workers
      nodeDrainTimeout: 0s
      version: v1.29.0
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3MachineTemplate
metadata:
  name: workload1-workers
  namespace: default
spec:
  nodeReuse: false
  template:
    spec:
      automatedCleaningMode: metadata
      dataTemplate:
        name: workload1-workers-template
      image:
        checksum: d92df03e7820c553ddcee2680d5d4798b4e7957fd0375b5d1d24b8241532082b
        checksumType: sha256
        format: qcow2
        url: http://192.168.40.241/UBUNTU_22.04_NODE_IMAGE_K8S_v1.29.0.qcow2
---
apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
kind: KubeadmConfigTemplate
metadata:
  name: workload1-workers
  namespace: default
spec:
  template:
    spec:
      joinConfiguration:
        nodeRegistration:
          kubeletExtraArgs:
            node-labels: metal3.io/uuid={{ ds.meta_data.uuid }}
          name: '{{ ds.meta_data.name }}'
      users:
      - name: user
        sshAuthorizedKeys:
        - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIFAVpbLhDAyF18/LDnRM1t5ZfMuFYgQlEBccATym2VH5
          root@compute-07
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: workload1-controlplane-template
  namespace: default
spec:
  clusterName: workload1
---
apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
kind: Metal3DataTemplate
metadata:
  name: workload1-workers-template
  namespace: default
spec:
  clusterName: workload1
